# Generated by Django 3.0.5 on 2020-04-10 21:59

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import sage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, sage.models.BaseComponent),
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MediaComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sage.Component')),
                ('media_type', models.CharField(choices=[('?', 'Unknown'), ('jpeg', 'Jpeg'), ('png', 'Png'), ('gif', 'Gif')], default='?', max_length=100)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/home/ego/gedanken-experimentieren/sage/sage_project/media/'), upload_to='')),
            ],
            bases=('sage.component',),
        ),
        migrations.CreateModel(
            name='TextComponent',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sage.Component')),
                ('content', models.TextField()),
            ],
            bases=('sage.component',),
        ),
        migrations.CreateModel(
            name='TextOrigin',
            fields=[
                ('origin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sage.Origin')),
                ('offset', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
            ],
            bases=('sage.origin',),
        ),
        migrations.CreateModel(
            name='ComponentRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sage.Origin')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left', to='sage.Component')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right', to='sage.Component')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='related',
            field=models.ManyToManyField(related_name='_component_related_+', through='sage.ComponentRelationship', to='sage.Component'),
        ),
    ]
